Implementation Of Visualization Framework
luisfpereira/geomfum pull request #14
Opened 2024-12-26 18:15 UTC by gviga

Hi,
I was thinking about how we can visualize shapes and came up with a proposal.
Since there are different libraries out there to plot meshes and point clouds and it seems that a lot of people use their favorite, I was thinking of developing a structure to define some 'Primitive' class, e.g a function to plot a mesh, that can be created in different ways using different libraries. 
From this idea comes the Shape/Mesh Plotter, which implements different functions depending on the selected library.

For now, I implemented a function to plot meshes using PyVista and Plotly (I still have problems with PyVista).

I'm curious about what you think about this idea and if my implementation for this kind of things makes sense.

2024-12-27 04:13 UTC, luisfpereira commented
Great job @gviga! I can see you get the main idea behind this package.

I've done a small git change here: this branch now starts from `main`, instead of `scalable-fm`.
This because they're independent and I believe we'll merge this before `scalable-fm`.
Please pull it locally again before merging any commit (you may need to delete your current `visual` and then do `git fetch`, `git switch -c visual origin/visual`).

Notice if you need any change available in other branch for testing purposes, you can always locally create a third branch and merge all the required branches. (Then remember to do commits only in the respective original branches.)

If you need that features for this code to work, then let's try to merge those other branches to main asap and merge `main` here.

I know this is annoying, but it makes things cleaner to develop/review.
When the package becomes more mature, this kind of weird development workflow will be avoided.

I'll make a proper review to this soon.

2024-12-27 04:27 UTC, luisfpereira requested changes
Great starting point @gviga!

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/plot.py
> +        '''
docstrings with `"""`.

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/wrap/__init__.py
> +    "plotly", "PlotlyMeshPlotter", requires="plotly", as_default=True
I believe the default of one of this should be `False`.

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/wrap/plotly.py
> +        fig.show()
let's return `fig` or the `plotter` in all the `plot` functions; users may want to perform further operations on these objects.

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/wrap/plotly.py
> +        f1,f2,f3= faces[:,0], faces[:,1], faces[:,2]
let's create a file `geomfum/shape/convert.py` and add this function there as `to_go_mesh3d` returning `go.Mesh3d`.

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/wrap/plotly.py
> +        f1,f2,f3= faces[:,0], faces[:,1], faces[:,2]
use new `to_go_mesh3d`

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/wrap/plotly.py
> +        #TODO: add assertion
maybe not necessary, plotting error should be clear

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/wrap/plotly.py
> +        #TODO: add parameters
most parameters may be defined at init, such as `colorscale`, as they'll be different for each plotter.

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/wrap/plotly.py
> +        fig.show()
maybe do not call show and expect plotter to have that method.

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/wrap/pyvista.py
> +        mesh = pv.PolyData(vertices, faces_formatted)
add `to_pv_polydata` to `geomfum.shape.convert`

2024-12-27 04:27 UTC, luisfpereira commented on geomfum/wrap/pyvista.py
> +        plotter.show()
same as above

2024-12-27 09:27 UTC, gviga commented on geomfum/wrap/plotly.py
> +        fig.show()
For the moment, I have implemented a show() function that displaying attributes instantiated by the plot function

2024-12-28 14:22 UTC, gviga commented
Hi @luisfpereira ,
I have developed your suggestions. I have implemented the two functions as functions that take as input meshes and outputs specific objects.

2024-12-31 06:36 UTC, luisfpereira commented on geomfum/shape/convert.py
> +    return pv.PolyData(mesh.vertices, faces_formatted)
```suggestion
    return pv.PolyData.from_regular_faces(points=mesh.vertices, faces=mesh.faces)
```

2025-01-27 14:17 UTC, gviga commented
Hi there, I have implemented a function to select indexes of points to select landmarks for shapes. I noticed we are missing a way to differentiate between point clouds and meshes at plotting time. Let me know if you have any ideas. However, I think we can start merging this code to have some basic implementation while we work on other parts.

2025-03-21 08:45 UTC, gviga commented
Hi guys,
I've added polyscope wrap
see https://polyscope.run/py/

2025-03-24 12:07 UTC, GiLonga commented
Hi Giulio,
I believe it would be better to merge the `pick_points` and `plot` functions, as `pick_points` enhances the functionality of `plot` in `plotly.py` and subsequently in `plot.py`.

2025-03-31 09:20 UTC, gviga commented
@luisfpereira We need to merge this and i think you have to review it in order to merge it

2025-04-28 23:13 UTC, luisfpereira commented
@GiLonga, thanks for the development of this module. I've done a bit of refactoring and am now merging.
Let me know if you disagree with any of my changes. If yes, please open a new PR with the proposed changes.

In my view, we should keep plotting as simple as possible, i.e. we should also provide a couple of fast ways to visualize important information. Other than that, I think people should use their own tools/frameworks, e.g. I'd go for pyvista for most of my visualizations.

2025-04-28 23:15 UTC, merged